### ISSUE TITLE
using your example config and getting contains no connector type

### ISSUE THREAD

**Issue by alberttwong** [aiven/http-connector-for-apache-kafka#168]
using https://dlcdn.apache.org/kafka/3.5.0/kafka_2.13-3.5.0.tgz

```
[2023-06-15 23:07:50,048] ERROR Failed to create connector for config/connect-http-sink.properties (org.apache.kafka.connect.cli.ConnectStandalone:74)
[2023-06-15 23:07:50,049] ERROR Stopping after connector error (org.apache.kafka.connect.cli.ConnectStandalone:84)
java.util.concurrent.ExecutionException: org.apache.kafka.connect.runtime.rest.errors.BadRequestException: Connector config {"http.authorization.type"="none",, "config"={, "connector.class"="io.aiven.kafka.connect.http.HttpSinkConnector",, "topics.regex"="domain_a.*",, "tasks.max"="1",, "http.url"="http://httpmockserver:1080",, "key.converter"="org.apache.kafka.connect.storage.StringConverter",, "name"="http-sink-test",, "batching.enabled"=true,, {=, "batch.max.size"=2,, "value.converter"="org.apache.kafka.connect.json.JsonConverter", }=} contains no connector type
	at org.apache.kafka.connect.util.ConvertingFutureCallback.result(ConvertingFutureCallback.java:123)
	at org.apache.kafka.connect.util.ConvertingFutureCallback.get(ConvertingFutureCallback.java:107)
	at org.apache.kafka.connect.cli.ConnectStandalone.processExtraArgs(ConnectStandalone.java:81)
	at org.apache.kafka.connect.cli.AbstractConnectCli.startConnect(AbstractConnectCli.java:150)
	at org.apache.kafka.connect.cli.AbstractConnectCli.run(AbstractConnectCli.java:94)
	at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:112)
Caused by: org.apache.kafka.connect.runtime.rest.errors.BadRequestException: Connector config {"http.authorization.type"="none",, "config"={, "connector.class"="io.aiven.kafka.connect.http.HttpSinkConnector",, "topics.regex"="domain_a.*",, "tasks.max"="1",, "http.url"="http://httpmockserver:1080",, "key.converter"="org.apache.kafka.connect.storage.StringConverter",, "name"="http-sink-test",, "batching.enabled"=true,, {=, "batch.max.size"=2,, "value.converter"="org.apache.kafka.connect.json.JsonConverter", }=} contains no connector type
	at org.apache.kafka.connect.runtime.AbstractHerder.validateConnectorConfig(AbstractHerder.java:468)
	at org.apache.kafka.connect.runtime.AbstractHerder.lambda$validateConnectorConfig$2(AbstractHerder.java:390)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2023-06-15 23:07:50,052] INFO Kafka Connect stopping (org.apache.kafka.connect.runtime.Connect:67)
[2023-06-15 23:07:50,052] INFO Stopping REST server (org.apache.kafka.connect.runtime.rest.RestServer:348)
[2023-06-15 23:07:50,057] INFO Stopped http_8083@4437ac07{HTTP/1.1, (http/1.1)}{0.0.0.0:8083} (org.eclipse.jetty.server.AbstractConnector:383)
[2023-06-15 23:07:50,058] INFO node0 Stopped scavenging (org.eclipse.jetty.server.session:149)
[2023-06-15 23:07:50,062] INFO REST server stopped (org.apache.kafka.connect.runtime.rest.RestServer:365)
[2023-06-15 23:07:50,062] INFO Herder stopping (org.apache.kafka.connect.runtime.standalone.StandaloneHerder:107)
[2023-06-15 23:07:50,063] INFO Worker stopping (org.apache.kafka.connect.runtime.Worker:223)
[2023-06-15 23:07:50,064] INFO Stopped FileOffsetBackingStore (org.apache.kafka.connect.storage.FileOffsetBackingStore:71)
[2023-06-15 23:07:50,064] INFO Metrics scheduler closed (org.apache.kafka.common.metrics.Metrics:693)
[2023-06-15 23:07:50,064] INFO Closing reporter org.apache.kafka.common.metrics.JmxReporter (org.apache.kafka.common.metrics.Metrics:697)
[2023-06-15 23:07:50,064] INFO Metrics reporters closed (org.apache.kafka.common.metrics.Metrics:703)
[2023-06-15 23:07:50,064] INFO App info kafka.connect for 172.31.9.192:8083 unregistered (org.apache.kafka.common.utils.AppInfoParser:83)
[2023-06-15 23:07:50,065] INFO Worker stopped (org.apache.kafka.connect.runtime.Worker:244)
[2023-06-15 23:07:50,066] INFO Herder stopped (org.apache.kafka.connect.runtime.standalone.StandaloneHerder:125)
[2023-06-15 23:07:50,066] INFO Kafka Connect stopped (org.apache.kafka.connect.runtime.Connect:72)
```

**Comment by alberttwong** [comment]
[root@ip-172-31-9-192 etc]# cat redhat-release
Red Hat Enterprise Linux release 9.2 (Plow)
[root@ip-172-31-9-192 kafka_2.13-3.5.0]# uname -a
Linux ip-172-31-9-192.us-west-2.compute.internal 5.14.0-284.11.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Apr 12 10:45:03 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux
[root@ip-172-31-9-192 kafka_2.13-3.5.0]# java -version
openjdk version "11.0.19" 2023-04-18 LTS
OpenJDK Runtime Environment (Red_Hat-11.0.19.0.7-2) (build 11.0.19+7-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-11.0.19.0.7-2) (build 11.0.19+7-LTS, mixed mode, sharing)

**Comment by alberttwong** [comment]
`bin/connect-standalone.sh config/connect-standalone.properties config/connect-http-sink.json`

connect-http-sink.json
```
{
  "name": "http-sink-test",
  "config": {
    "connector.class": "io.aiven.kafka.connect.http.HttpSinkConnector",
    "topics.regex": "domain_a.*",
    "http.authorization.type": "none",
    "http.url": "http://httpmockserver:1080",
    "batching.enabled": true,
    "batch.max.size": 2,
    "tasks.max": "1",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "value.converter": "org.apache.kafka.connect.json.JsonConverter"
  }
}
```

**Comment by alberttwong** [comment]
It would only work when I do

connect-http-sink.properties
```
name=http-sink-test
connector.class=io.aiven.kafka.connect.http.HttpSinkConnector
topics.regex=domain_a.*
http.authorization.type=none
http.url=http://httpmockserver:1080
batching.enabled=true
batch.max.size=2
tasks.max=1
key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
```

**Comment by alberttwong** [comment]
okay.. it wasn't clear in the instructions that you submit the json into the Kafka REST api.

```
curl -d @config/connect-http-sink.json    -H "Content-Type: application/json"   -X POST http://localhost:8083/connector
```

**Comment by ivanyu** [comment]
Hi @alberttwong.
Yes, you're right, the JSON config example is for the API. We assume connectors are mostly created this way so we preferred to use JSON over the plain format in the documentation.

**Comment by alberttwong** [comment]
https://github.com/aiven/http-connector-for-apache-kafka/pull/169
